version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      #platform: linux/amd64
    #environment:
    #  MYENV: env1000
    ports:
      - 8000:8000
    volumes:
      #- ./db.sqlite3
      - .:/app
     
 
