apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: my-python-app
        image: sktregistry.azurecr.io/azuredocs/github-to-docker-practice
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
