export const BLACK_LOGIN_REQUEST = 'BLACK_LOGIN_REQUEST'
export const BLACK_LOGIN_SUCCESS = 'BLACK_LOGIN_SUCCESS'
export const BLACK_LOGIN_FAIL = 'BLACK_LOGIN_FAIL'

export const BLACK_LOGOUT = 'BLACK_LOGOUT'

export const BLACK_REGISTER_REQUEST = 'BLACK_REGISTER_REQUEST'
export const BLACK_REGISTER_SUCCESS = 'BLACK_REGISTER_SUCCESS'
export const BLACK_REGISTER_FAIL = 'BLACK_REGISTER_FAIL'

export const BLACK_DETAILS_REQUEST = 'BLACK_DETAILS_REQUEST'
export const BLACK_DETAILS_SUCCESS = 'BLACK_DETAILS_SUCCESS'
export const BLACK_DETAILS_FAIL = 'BLACK_DETAILS_FAIL'
export const BLACK_DETAILS_RESET = 'BLACK_DETAILS_RESET'

export const BLACK_UPDATE_PROFILE_REQUEST = 'BLACK_UPDATE_PROFILE_REQUEST'
export const BLACK_UPDATE_PROFILE_SUCCESS = 'BLACK_UPDATE_PROFILE_SUCCESS'
export const BLACK_UPDATE_PROFILE_FAIL = 'BLACK_UPDATE_PROFILE_FAIL'
export const BLACK_UPDATE_PROFILE_RESET = 'BLACK_UPDATE_PROFILE_RESET'

export const BLACK_LIST_REQUEST = 'BLACK_LIST_REQUEST'
export const BLACK_LIST_SUCCESS = 'BLACK_LIST_SUCCESS'
export const BLACK_LIST_FAIL = 'BLACK_LIST_FAIL'
export const BLACK_LIST_RESET = 'BLACK_LIST_RESET'


export const BLACK_DELETE_REQUEST = 'BLACK_DELETE_REQUEST'
export const BLACK_DELETE_SUCCESS = 'BLACK_DELETE_SUCCESS'
export const BLACK_DELETE_FAIL = 'BLACK_DELETE_FAIL'


export const BLACK_UPDATE_REQUEST = 'BLACK_UPDATE_REQUEST'
export const BLACK_UPDATE_SUCCESS = 'BLACK_UPDATE_SUCCESS'
export const BLACK_UPDATE_FAIL = 'BLACK_UPDATE_FAIL'
export const BLACK_UPDATE_RESET = 'BLACK_UPDATE_RESET'