# Generated by Django 4.1 on 2022-08-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_positive",
            field=models.BinaryField(null=True),
        ),
    ]
