# Generated by Django 4.1 on 2022-08-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_review_is_positive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="is_positive",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
