# Generated by Django 3.1.4 on 2022-08-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_review_is_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
