# Generated by Django 3.1.4 on 2022-09-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_review_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wordcloud',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='review',
            name='wordcloud',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
