# Generated by Django 3.1.4 on 2022-09-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='datetime',
            field=models.TextField(blank=True, null=True),
        ),
    ]
