# Generated by Django 3.1.4 on 2022-09-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220901_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
